apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: threadmem-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: threadmem-secrets
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: threads-encryption-key
