apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: cert.yaml
    target:
      kind: ManagedCertificate
  - path: ingress.yaml
    target:
      kind: Ingress
